% This program is to calcualte the emperical cdf of the statistic Eta by
% Szekely and Rizzo for multi-norm test with data generated by MVN(0,Sigma), where the
% default Sigma is set to be identity matrix.

% 2010-4-15 by Chun-Chao Wang
clear

% RandStream.setDefaultStream(RandStream('mt19937ar','seed',sum(100*clock)));
n_samples=[20];
% n_samples=[10:3:199 250 300 500];
N=10000;% emperical samples
N_batch=1000;
n_divide=N/N_batch;
rho=0;% Indicate Standard MVN
k_variate=input('K-variate :');%2:10;%k-variate
m=10000;
% q=[1/m 0.01:0.01:0.2];% qth quantile, 1/m means the minimum, p can be a vector for multiple quantiles
q=0.05;
tic
for k=k_variate
    mu=zeros(1,k);
    Sigma=eye(k);Sigma(Sigma==0)=rho;%equal rho
    for n=n_samples
        fprintf('Processing for sample size n=%3.0f..k=%3.0f......\n',n,k);pause(1);    
        W_MA=zeros(N,length(q)); 
        for j=1:n_divide
            Y=mvnrnd(mu, Sigma, n*N_batch);
            for i=1:N_batch
                X=Y(((i-1)*n+1):i*n,:);
                W_MA(i+(j-1)*N_batch,:)=multi_norm_percentile_simu(X,m,q);                
            end
        end
        for i=1:length(q)
            [YCDF,XCDF] = ecdf(W_MA(:,i));
            if q(i)<0.01
                tmp='min';
            else
                tmp=num2str(100*q(i));
            end
%             if rho==0% use normalized data
%                 str=strcat('save data/WMA_N_I_percentile_',tmp,'_k',num2str(k),'_',num2str(n), ' XCDF YCDF');
%             else% use non-normalized data
%                 str=strcat('save data/WMA_N_percentile_',tmp,'_k',num2str(k),'_',num2str(n), ' XCDF YCDF');
%             end
%             eval(str);
        end
    end
end
toc